/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import hr.algebra.dal.IUserRepo;
import hr.algebra.dal.SessionManager;
import hr.algebra.dal.UserRepoFactory;
import hr.algebra.dal.sql.UserRepo;
import hr.algebra.model.User;
import hr.algebra.view.AdminControlsPanel;
import hr.algebra.view.EditActorsPanel;
import hr.algebra.view.EditDirectorsPanel;
import hr.algebra.view.EditMoviesPanel;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ante Prskalo
 */
public class CoolMovie extends javax.swing.JFrame {

    private SessionManager sessionManager;

    private static final String EDIT_MOVIES = "Edit movies";
    private static final String EDIT_ACTORS = "Edit actors";
    private static final String EDIT_DIRECTORS = "Edit directors";
    private static final String ADMIN_PANEL = "Admin";

    /**
     * Creates new form CoolMovie
     */
    public CoolMovie() throws Exception {
        this.sessionManager = sessionManager;
        initComponents();
        configurePanels();
        setUserPermissions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Movie Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoolMovie.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoolMovie.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoolMovie.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoolMovie.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CoolMovie().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CoolMovie.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void setUserPermissions() {
        if (sessionManager.getLoggedUser()
                .map(User::getUserRole)
                .orElse("")
                .equals("admin")) {
            tpContent.add(ADMIN_PANEL, new AdminControlsPanel());
        }
    }

    private void configurePanels() {
        tpContent.add(EDIT_MOVIES, new EditMoviesPanel());
        tpContent.add(EDIT_ACTORS, new EditActorsPanel());
        tpContent.add(EDIT_DIRECTORS, new EditDirectorsPanel());
    }
}
